version: '3'

services:
  database:
    image: postgres:16.1-alpine3.19
    ports:
      - 15432:5432
    env_file:
      - .env
    volumes:
      - ./db-data/:/var/lib/postgresql/data/
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
